gText_Birch_Welcome::
    .string "Hi! You seem to be new here...\p"
    .string "Welcome to the region of Kemetra!\p"
    .string "My name is Professor Selket.\p"
    .string "I will be your guide in the Trials of Ma'at,\n"
    .string "where balance and truth are tested.\p"
    .string "$"

gText_Birch_Pokemon::
    .string "This is what we call a “POKéMON.”\p"
    .string "$"

gText_Birch_MainSpeech::
    .string "This world teeters between\n"
    .string "light and shadow,\p"
	.string "and the eternal darkness of the Duat.\p"
    .string "Creatures known as POKéMON walk among us\n"
    .string "as guardians, \p"
    .string "and divine companions.\p"
    .string "We humans live beside them,\n"
    .string "sometimes as allies, sometimes as rivals.\p"
    .string "Together, we explore, trade, and battle,\n"
    .string "seeking the favor of the gods.\p"
    .string "Yet much about POKéMON remains buried\n"
    .string "beneath the sands of time.\p"
    .string "I have dedicated my life to unearthing\n"
    .string "their secrets and powers.\p"
    .string "That's my calling.\p"
    .string "$"


gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, i see!\p"
	.string "You're {PLAYER}{KUN}, the traveler who's moving to \n"
	.string "the Serkah Village.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you.\n"
	.string "Come I'll be waiting...\p"
	.string "$"
